# Generated by Django 3.2.7 on 2021-09-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
